main: me.kxmpxtxnt.paypaul.PayPaul
version: 1.0
name: PayPaul
description: Just a Paypal fake in Minecraft :D
authors:
  - Lillys
  - next
  - intern
api-version: 1.18
commands:
  paypaul:
    description: Paypaul-Command | Main command of the plugin